# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'C-19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for C-19
pod 'Charts'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

end
